default_agent: arise_email
agents:
  arise_email:
    name: arise_email
    language: python
    node_version: null
    entrypoint: agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: .
    aws:
      execution_role: arn:aws:iam::436776987862:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-331c7a03e7
      execution_role_auto_create: false
      account: '436776987862'
      region: us-west-2
      ecr_repository: 436776987862.dkr.ecr.us-west-2.amazonaws.com/arise-email-agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: arise_email-prFvYN2bd3
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:436776987862:runtime/arise_email-prFvYN2bd3
      agent_session_id: ac0a92f7-ba1a-4781-8d02-e4d7472db63f
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
